window.VOCAB_DATA = [
  ["une histoire","eine Geschichte","C'est une histoire amusante."],
  ["il y a","es hat, es gibt","Il y a un accident."],
  ["un accident","ein Unfall","La cloche sonne."],
  ["la cloche","die Glocke","La cloche sonne."],
  ["sonner","klingeln, läuten","La cloche sonne."],
  ["le prof/la prof","der Lehrer/die Lehrerin","La prof est dans la salle de classe."],
  ["la salle de classe","das Schulzimmer","La prof est dans la salle de classe."],
  ["la récréation","die Pause","La cloche sonne, c'est la récréation!"],
  ["d'abord","zuerst","D'abord, je me douche."],
  ["ensuite","dann, danach, anschliessend","Ensuite, je prépare mon sac à dos."],
  ["finalement","schliesslich, letztlich","Finalement, je quitte la maison."],
  ["J'ouvre la porte.","Ich öffne die Tür.",""],
  ["la clé","der Schlüssel","Elles cherchent la clé."],
  ["casser","kaputt machen, zerbrechen","Je casse une fenêtre."],
  ["Il pleut.","Es regnet.",""],
  ["fatigué/e","müde","Il est fatigué."],
  ["avoir","haben","Nous avons un test."],

  ["Je me lève à 6h30.","Ich stehe um 6.30 Uhr auf.",""],
  ["le réveil","der Wecker","Le réveil sonne."],
  ["se réveiller","aufwachen, erwachen","Je me réveille et je me rase."],
  ["se raser","sich rasieren","Je me réveille et je me rase."],
  ["aussi vite que possible","so schnell wie möglich","Je me lève aussi vite que possible."],
  ["glander","herumhängen, trödeln, herumlungern","Le matin, il glande."],
  ["le temps","die Zeit, das Wetter","Je glande et j'oublie le temps."],
  ["quitter la maison","das Haus verlassen","Je quitte la maison et je prends le bus."],
  ["et","und","Je quitte la maison et je prends le bus."],
  ["Je prends le bus.","Ich nehme den Bus.",""],
  ["arriver en retard","zu spät (an)kommen","Elle arrive en retard à l'école."],
  ["à l'école (f)","in der Schule, in die Schule","Elle arrive en retard à l'école."],
  ["le copain/la copine","der Kollege/die Kollegin","Les copains s'amusent sur le chemin de l'école."],
  ["s'amuser","sich lustig haben, sich vergnügen","Les copains s'amusent sur le chemin de l'école."],
  ["sur le chemin de l'école","auf dem Schulweg","Les copains s'amusent sur le chemin de l'école."],
  ["Je suis relax.","Ich bin locker, entspannt.",""],
  ["content/e","zufrieden, erfreut, froh",""],
  ["stressé/e","gestresst",""],
  ["nerveux/euse","nervös",""],
  ["énervé/e","genervt",""],
  ["gentil/gentille","nett",""],
  ["avoir peur","Angst haben","J'ai peur."],
  ["c'est horrible","das/es ist schrecklich","C'est horrible, je panique."],
  ["paniquer","in Panik geraten","C'est horrible, je panique."],

  ["rester au lit","im Bett bleiben","Ce matin, je reste au lit."],
  ["dans la salle de bains","im/ins Badezimmer","Dans la salle de bains, je me lave le visage."],
  ["se laver le visage","sich das Gesicht waschen","Dans la salle de bains, je me lave le visage."],
  ["s'habiller","sich anziehen","Je m'habille et ensuite, je me coiffe."],
  ["se coiffer","sich frisieren","Je m'habille et ensuite, je me coiffe."],
  ["se maquiller","sich schminken","Je me maquille dans la salle de bains."],
  ["manger","essen","Tu manges un bon petit-déjeuner."],
  ["le petit-déjeuner","das Frühstück","Tu manges un bon petit-déjeuner."],
  ["se brosser les dents","sich die Zähne putzen","Ensuite, nous nous brossons les dents."],
  ["préparer son sac à dos","den Rucksack bereit machen","Je prépare rapidement mon sac à dos."],
  ["rapidement","schnell","Je prépare rapidement mon sac à dos."],
  ["chercher","suchen","Je cherche les affaires d'école."],
  ["trouver","finden","Je ne trouve pas la clé."],
  ["oublier","vergessen","Elle oublie le livre de français à la maison."],
  ["le livre de français","das Französischbuch","Elle oublie le livre de français à la maison."],
  ["les affaires d'école (f pl)","die Schulsachen","Je cherche les affaires d'école."],
  ["réviser pour le test d'anglais","für den Englischtest üben",""],
  ["jouer sur son portable","auf dem Handy spielen","Ma sœur joue sur son portable."],
  ["Je vais à l'école à vélo.","Ich gehe mit dem Velo zur Schule.",""],
  ["Je vais à pied.","Ich gehe zu Fuss.",""],
  ["rater le bus","den Bus verpassen","Je rate le bus."],
  ["trop tard","zu spät","J'arrive trop tard à l'école."],
  ["tôt","früh","Je me lève tôt."],
  ["seulement","nur","Il me reste seulement trois minutes: je me dépêche."],
  ["se dépêcher","sich beeilen","Il me reste seulement trois minutes: je me dépêche."],
  ["s'excuser","sich entschuldigen","Je m'excuse auprès de la prof."],
  ["la sœur","die Schwester","Ma sœur joue sur son portable."],
  ["le frère","der Bruder",""],
  ["les parents (m pl)","die Eltern","Je me dispute avec mes parents."],
  ["se disputer","sich streiten","Je me dispute avec mes parents."],
  ["crier","schreien, brüllen","Mon père crie."]
];
